#!/bin/bash
#set -x

if [ -z "$PROJECT" ]; then
    echo "can't $0, no PROJECT found in the environment"
    exit 1;
fi
if [ -z "$PHOME" ]; then
    echo "can't $0, no PHOME found in the environment"
    exit 1;
fi
CommitMessage="$1"
if [ -z "$CommitMessage" ]; then
    echo "no commit message, enter it now:"
    read CommitMessage
    if [ -z "$CommitMessage" ]; then
        echo "no commit message, exiting"
        exit 1;
     fi
fi

pushd "$PHOME" > /dev/null
#pushd "$PHOME" 

# make clean any directories with a make file
find . \
     -not -path "./.git/*" \
     -not -path "./tmp/*" \
     -type f \
     -name 'makefile' \
     -execdir make clean \;

# suffix a '~' to any executables that don't already have one
find . \
     -not -path "./.git/*" \
     -not -path "./tmp/*" \
     -not -name '*~'\
     -type f \
     -executable \
     -exec echo "suffixing ~ to executable " {} \; \
     -execdir mv {} {}~ \;

git add . && git commit -m "$CommitMessage" && git push || echo "push failed"

popd > /dev/null
#popd

#set +x
