#!/bin/sh
#
# rm_tilda_files_dir .
#

if [ ! -d "$1" ]; then
  echo "expected first arg to be a directory where rm_tilda_files_dir is to be applied, but found: " "$1"
  exit 1
fi

find "$1" -maxdepth 1 -name '*~' -exec rm {} \;

