#!/bin/bash
#
# sed_dir . -f myscript.sed
#

if [ ! -d "$1" ]; then
  echo "expected first arg to be a directory where sed is to be applied, but found: " "$1"
  exit 1
fi

dir="$1"
shift

find "$dir" -maxdepth 1 -type f -exec sed -i~ {} "$@" \;
