#!/bin/bash
#
# sed_tree . -f myscript.sed
#

if [ ! -d "$1" ]; then
  echo "expected first arg to be a directory where sed is to be applied, but found: " "$1"
  exit 1
fi

dir="$1"
shift

find "$dir" -type f -not -path '*/\.git/*' -exec sed -i {} "$@" \;
