#!/bin/bash
#set -x

if [ -z "$REPO_DIR" ]; then
    echo "can't $0, no REPO_DIR found in the environment"
    exit 1;
fi
CommitMessage="$1"
if [ -z "$CommitMessage" ]; then
    echo "no commit message, enter it now:"
    read CommitMessage
    if [ -z "$CommitMessage" ]; then
        echo "no commit message, exiting"
        exit 1;
     fi
fi

pushd "$REPO_DIR" > /dev/null

  # make clean any directories with a makefile
  find . \
       -not -path "./.git/*" \
       -not -path "./tmp/*" \
       -type f \
       -name 'makefile' \
       -execdir make clean \;

  # executables should not be checked into the repo, yet we found these:
  find . \
       -not -path "./.git/*" \
       -not -path "./tmp/*" \
       -type f \
       -executable \
       -exec echo "found executable, removing x flag" {} \; 
       -execdir chmod -x {} \;

  #     -execdir mv {} {}~ \;

set -x
  git stash
  git pull
  git stash pop
  git add .
  git commit -m "$CommitMessage"
  git push
set +x

popd > /dev/null
#set +x



